[package]
name = "addin-image-converter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
addin1c = "0.5"
image = "0.25"
